root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/server"
bin = "./tmp/main"
full_bin = ""
include_ext = ["go", "tpl", "tmpl", "html", "css", "js"]
exclude_dir = ["assets", "tmp", "vendor"]
include_dir = []
exclude_file = []
delay = 1000
stop_on_error = true
log = "air_errors.log"
send_interrupt = false
kill_delay = 500

[log]
time = true
main_only = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true

[live_reload]
enabled = true
port = 35729
patterns = ["**/*.html", "**/*.css", "**/*.js"] 